#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXqlvt
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QLVT")]
	public partial class ThongtinvanbannoiboDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public ThongtinvanbannoiboDataContext() : 
				base(global::DXqlvt.Properties.Settings.Default.QLVTConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public ThongtinvanbannoiboDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ThongtinvanbannoiboDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ThongtinvanbannoiboDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ThongtinvanbannoiboDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<View_1> View_1s
		{
			get
			{
				return this.GetTable<View_1>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.View_1")]
	public partial class View_1
	{
		
		private int _id;
		
		private string _Kihieu;
		
		private string _TenLVB;
		
		private string _TenNBH;
		
		private string _Linhvuc;
		
		private int _Sotrang;
		
		private int _Soban;
		
		private string _Filetaptin;
		
		private string _NoidungVB;
		
		private string _Trichyeu;
		
		private System.DateTime _Ngaytao;
		
		private string _TenVB;
		
		private string _Noinhan;
		
		public View_1()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL")]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this._id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Kihieu", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string Kihieu
		{
			get
			{
				return this._Kihieu;
			}
			set
			{
				if ((this._Kihieu != value))
				{
					this._Kihieu = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenLVB", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string TenLVB
		{
			get
			{
				return this._TenLVB;
			}
			set
			{
				if ((this._TenLVB != value))
				{
					this._TenLVB = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenNBH", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string TenNBH
		{
			get
			{
				return this._TenNBH;
			}
			set
			{
				if ((this._TenNBH != value))
				{
					this._TenNBH = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Linhvuc", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string Linhvuc
		{
			get
			{
				return this._Linhvuc;
			}
			set
			{
				if ((this._Linhvuc != value))
				{
					this._Linhvuc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sotrang", DbType="Int NOT NULL")]
		public int Sotrang
		{
			get
			{
				return this._Sotrang;
			}
			set
			{
				if ((this._Sotrang != value))
				{
					this._Sotrang = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Soban", DbType="Int NOT NULL")]
		public int Soban
		{
			get
			{
				return this._Soban;
			}
			set
			{
				if ((this._Soban != value))
				{
					this._Soban = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Filetaptin", DbType="NVarChar(100)")]
		public string Filetaptin
		{
			get
			{
				return this._Filetaptin;
			}
			set
			{
				if ((this._Filetaptin != value))
				{
					this._Filetaptin = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoidungVB", DbType="NVarChar(1000) NOT NULL", CanBeNull=false)]
		public string NoidungVB
		{
			get
			{
				return this._NoidungVB;
			}
			set
			{
				if ((this._NoidungVB != value))
				{
					this._NoidungVB = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Trichyeu", DbType="NVarChar(1000) NOT NULL", CanBeNull=false)]
		public string Trichyeu
		{
			get
			{
				return this._Trichyeu;
			}
			set
			{
				if ((this._Trichyeu != value))
				{
					this._Trichyeu = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ngaytao", DbType="Date NOT NULL")]
		public System.DateTime Ngaytao
		{
			get
			{
				return this._Ngaytao;
			}
			set
			{
				if ((this._Ngaytao != value))
				{
					this._Ngaytao = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenVB", DbType="NVarChar(100)")]
		public string TenVB
		{
			get
			{
				return this._TenVB;
			}
			set
			{
				if ((this._TenVB != value))
				{
					this._TenVB = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Noinhan", DbType="NVarChar(1000)")]
		public string Noinhan
		{
			get
			{
				return this._Noinhan;
			}
			set
			{
				if ((this._Noinhan != value))
				{
					this._Noinhan = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
