<?xml version="1.0" encoding="utf-8"?><Database Name="QLVT" Class="ThongtinnoibanhanhDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DESKTOP-7SU81BF\\SQLEXPRESS;Initial Catalog=QLVT;Integrated Security=True" SettingsObjectName="DXqlvt.Properties.Settings" SettingsPropertyName="QLVTConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.noibanhanh" Member="noibanhanhs">
    <Type Name="noibanhanh">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenNBH" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Ghichu" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>